### PR TITLE
Added resume to contact info

### PR DESCRIPTION
**Pull request by laura333**

### CODE REVIEW

**Comment by AnalogGhost** [comment]
You have a merge conflict with a .DS_Store file.  We need to resolve before merging.

**Comment by laura333** [comment]
I deleted the .DS_Store from my directory since it's an unnecessary file. (I was told to always delete those.) I don't have access to resolve the conflict on GitHub. When I get to class I'll resolve it in Atom if I can.

**Comment by AnalogGhost** [comment]
I cleaned the file and was able to merge.

**Comment by laura333** [comment]
Thank you!

**Pull request merged**
